import CoreGraphics
import Foundation

/// Codable rectangle model used in wake-cycle scenario state files.
public struct CodableRect: Codable, Equatable, Sendable {
    public let x: Double
    public let y: Double
    public let width: Double
    public let height: Double

    /// Creates a codable rectangle from scalar coordinates.
    public init(x: Double, y: Double, width: Double, height: Double) {
        self.x = x
        self.y = y
        self.width = width
        self.height = height
    }

    /// Creates a codable rectangle from a CoreGraphics rectangle.
    public init(_ rect: CGRect) {
        self.init(
            x: rect.origin.x,
            y: rect.origin.y,
            width: rect.width,
            height: rect.height
        )
    }

    /// Converts back to CoreGraphics coordinates.
    public var cgRect: CGRect {
        CGRect(x: x, y: y, width: width, height: height)
    }
}

/// Persisted identity and placement target for a single tracked window.
public struct TrackedWindow: Codable, Equatable, Sendable {
    public let appBundleID: String?
    public let titleHint: String
    public let expectedDisplayID: UInt32
    public let expectedFrame: CodableRect

    /// Creates a tracked-window entry for scenario persistence and verification.
    public init(
        appBundleID: String?,
        titleHint: String,
        expectedDisplayID: UInt32,
        expectedFrame: CodableRect
    ) {
        self.appBundleID = appBundleID
        self.titleHint = titleHint
        self.expectedDisplayID = expectedDisplayID
        self.expectedFrame = expectedFrame
    }
}

/// Persisted state generated by `prepare` and consumed by `verify`.
public struct ScenarioState: Codable, Equatable, Sendable {
    public let scenario: String
    public let bundleID: String
    public let trackedBundleIDs: [String]?
    public let preparedAt: Date
    public let trackedWindows: [TrackedWindow]
    public let createdPaths: [String]

    /// Creates a persisted scenario state record.
    public init(
        scenario: String,
        bundleID: String,
        trackedBundleIDs: [String]?,
        preparedAt: Date,
        trackedWindows: [TrackedWindow],
        createdPaths: [String]
    ) {
        self.scenario = scenario
        self.bundleID = bundleID
        self.trackedBundleIDs = trackedBundleIDs
        self.preparedAt = preparedAt
        self.trackedWindows = trackedWindows
        self.createdPaths = createdPaths
    }
}

/// Persisted verification report generated by `verify`.
public struct ScenarioReport: Codable, Equatable, Sendable {
    public let scenario: String
    public let verifiedAt: Date
    public let passed: Bool
    public let details: [String]

    /// Creates a persisted scenario verification report.
    public init(
        scenario: String,
        verifiedAt: Date,
        passed: Bool,
        details: [String]
    ) {
        self.scenario = scenario
        self.verifiedAt = verifiedAt
        self.passed = passed
        self.details = details
    }
}

/// JSON codec for persisted `ScenarioState` files.
public enum ScenarioStateCodec {
    /// Encodes scenario state with stable key ordering and ISO-8601 dates.
    public static func encode(_ state: ScenarioState) throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        return try encoder.encode(state)
    }

    /// Decodes scenario state from JSON using ISO-8601 dates.
    public static func decode(_ data: Data) throws -> ScenarioState {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode(ScenarioState.self, from: data)
    }
}

/// JSON codec for persisted `ScenarioReport` files.
public enum ScenarioReportCodec {
    /// Encodes scenario report with stable key ordering and ISO-8601 dates.
    public static func encode(_ report: ScenarioReport) throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        return try encoder.encode(report)
    }

    /// Decodes scenario report from JSON using ISO-8601 dates.
    public static func decode(_ data: Data) throws -> ScenarioReport {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode(ScenarioReport.self, from: data)
    }
}
